//request user infomation
export const REQUEST_USERINFO = 'REQUEST_USERINFO';
export const REQUEST_USERINFO_SUCCESS = 'REQUEST_USERINFO_SUCCESS';
export const REQUEST_USERINFO_FAIL = 'REQUEST_USERINFO_FAIL';

export const UPDATE_USERPROF = 'UPDATE_USERPROF';
export const UPDATE_USERPROF_SUCCESS = 'UPDATE_USERPROF_SUCCESS';
export const UPDATE_USERPROF_FAIL = 'UPDATE_USERPROF_FAIL';

export const UPDATE_USERINFO_TICKETS = 'UPDATE_USERINFO_TICKETS';
export const UPDATE_USERINFO_RESERVATION = 'UPDATE_USERINFO_RESERVATION';

export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';

//message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//timetable
export const SET_TYPE_STATUS = 'SET_TYPE_STATUS';
export const CHANGE_TYPE_CHECKED = 'CHANGE_TYPE_CHECKED';

export const SET_PLACE_STATUS = 'SET_PLACE_STATUS';
export const CHANGE_PLACE_ACTIVE = 'CHANGE_PLACE_ACTIVE';
export const CHANGE_PLACE_CHECKED = 'CHANGE_PLACE_CHECKED';

export const CHANGE_WEEK = 'CHANGE_WEEK';

export const REQUEST_TIMETABLE = 'REQUEST_TIMETABLE';
export const REQUEST_TIMETABLE_SUCCESS = 'REQUEST_TIMETABLE_SUCCESS';
export const REQUEST_TIMETABLE_FAIL = 'REQUEST_TIMETABLE_FAIL';
export const TIMETABLE_IS_OLD = 'TIMETABLE_IS_OLD';

export const MODAL_ON = 'MODAL_ON';
export const MODAL_OFF = 'MODAL_OFF';

export const SET_RESERVATION = 'SET_RESERVATION';
export const ADD_RESERVATION = 'ADD_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';

//ticket
export const CHANGE_TICKET_PANEL = 'CHANGE_TICKET_PANEL';

export const REQUEST_TICKET = 'REQUEST_TICKET';
export const REQUEST_TICKET_SUCCESS = 'REQUEST_TICKET_SUCCESS';
export const REQUEST_TICKET_FAIL = 'REQUEST_TICKET_FAIL';

//log
export const REQUEST_LOG = 'REQUEST_LOG';
export const REQUEST_LOG_SUCCESS = 'REQUEST_LOG_SUCCESS';
export const REQUEST_LOG_FAIL = 'REQUEST_LOG_FAIL';