//request user infomation
export const REQUEST_USERINFO = 'REQUEST_USERINFO';
export const REQUEST_USERINFO_SUCCESS = 'REQUEST_USERINFO_SUCCESS';
export const REQUEST_USERINFO_FAIL = 'REQUEST_USERINFO_FAIL';

export const SET_TYPE_STATUS = 'SET_TYPE_STATUS';
export const CHANGE_TYPE_CHECKED = 'CHANGE_TYPE_CHECKED';

export const SET_PLACE_STATUS = 'SET_PLACE_STATUS';
export const CHANGE_PLACE_ACTIVE = 'CHANGE_PLACE_ACTIVE';
export const CHANGE_PLACE_CHECKED = 'CHANGE_PLACE_CHECKED';

export const CHANGE_WEEK = 'CHANGE_WEEK';

export const REQUEST_TIMETABLE = 'REQUEST_TIMETABLE';
export const REQUEST_TIMETABLE_SUCCESS = 'REQUEST_TIMETABLE_SUCCESS';
export const REQUEST_TIMETABLE_FAIL = 'REQUEST_TIMETABLE_FAIL';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const MODAL_ON = 'MODAL_ON';
export const MODAL_OFF = 'MODAL_OFF';

export const SET_RESERVATION = 'SET_RESERVATION';
export const ADD_RESERVATION = 'ADD_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';

//ticket
export const CHANGE_TICKET_PANEL = 'CHANGE_TICKET_PANEL';
