//page status
export const CANGE_LANG = 'CANGE_LANG';
export const SIDEVAR_ON = 'SIDEVAR_ON';
export const SIDEVAR_OFF = 'SIDEVAR_OFF';
export const CHANGE_SIDEVAR = 'CHANGE_SIDEVAR';

//request my profile
export const REQUEST_MY_PROFILE = 'REQUEST_MY_PROFILE';
export const REQUEST_MY_PROFILE_SUCCESS = 'REQUEST_MY_PROFILE_SUCCESS';
export const REQUEST_MY_PROFILE_FAIL = 'REQUEST_MY_PROFILE_FAIL';

//alert
export const ADD_ACCESS_ALERT = 'ADD_ACCESS_ALERT';
export const DELETE_ACCESS_ALERT = 'DELETE_ACCESS_ALERT';

//disposable
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_VALIDATION = 'ADD_VALIDATION';
export const CLEAR_DISPOSABLE = 'CLEAR_DISPOSABLE';


//Access user
export const REQUEST_USERS = 'REQUEST_USERS';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAIL = 'REQUEST_USERS_FAIL';
export const REQUEST_USER = 'REQUEST_USER';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAIL = 'REQUEST_USER_FAIL';
export const DO_ASYNC_ACTION = 'DO_ASYNC_ACTION';
export const DONE_ASYNC_ACTION = 'DONE_ASYNC_ACTION';
//Access roles
export const REQUEST_ROLES = 'REQUEST_ROLES';
export const REQUEST_ROLES_SUCCESS = 'REQUEST_ROLES_SUCCESS';
export const REQUEST_ROLES_FAIL = 'REQUEST_ROLES_FAIL';
export const DO_ROLE_ASYNC_ACTION = 'DO_ROLE_ASYNC_ACTION';
export const DONE_ROLE_ASYNC_ACTION = 'DONE_ROLE_ASYNC_ACTION';
//Access permissions
export const REQUEST_PERMISSIONS = 'REQUEST_PERMISSIONS';
export const REQUEST_PERMISSIONS_SUCCESS = 'REQUEST_PERMISSIONS_SUCCESS';
export const REQUEST_PERMISSIONS_FAIL = 'REQUEST_PERMISSIONS_FAIL';
export const REQUEST_PERMISSION_DEPENDENCY_SUCCESS = 'REQUEST_PERMISSION_DEPENDENCY_SUCCESS';
export const REQUEST_PERMISSION_DEPENDENCY_FAIL = 'REQUEST_PERMISSION_DEPENDENCY_FAIL';

export const ADD_DEPENDENCY = 'ADD_DEPENDENCY';
export const CLEAR_DEPENDENCY = 'CLEAR_DEPENDENCY';

export const DO_PERMISSION_ASYNC_ACTION = 'DO_PERMISSION_ASYNC_ACTION';
export const DONE_PERMISSION_ASYNC_ACTION = 'DONE_PERMISSION_ASYNC_ACTION';






export const UPDATE_USERINFO_TICKETS = 'UPDATE_USERINFO_TICKETS';
export const UPDATE_USERINFO_RESERVATION = 'UPDATE_USERINFO_RESERVATION';

export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';

//message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//timetable
export const SET_TYPE_STATUS = 'SET_TYPE_STATUS';
export const CHANGE_TYPE_CHECKED = 'CHANGE_TYPE_CHECKED';

export const SET_PLACE_STATUS = 'SET_PLACE_STATUS';
export const CHANGE_PLACE_ACTIVE = 'CHANGE_PLACE_ACTIVE';
export const CHANGE_PLACE_CHECKED = 'CHANGE_PLACE_CHECKED';

export const CHANGE_WEEK = 'CHANGE_WEEK';

export const REQUEST_TIMETABLE = 'REQUEST_TIMETABLE';
export const REQUEST_TIMETABLE_SUCCESS = 'REQUEST_TIMETABLE_SUCCESS';
export const REQUEST_TIMETABLE_FAIL = 'REQUEST_TIMETABLE_FAIL';
export const TIMETABLE_IS_OLD = 'TIMETABLE_IS_OLD';
export const SET_PLANS = 'SET_PLANS';

export const MODAL_ON = 'MODAL_ON';
export const MODAL_OFF = 'MODAL_OFF';

//reservations
export const REQUEST_RESERVATIONS = 'REQUEST_RESERVATIONS';
export const REQUEST_RESERVATIONS_SUCCESS = 'REQUEST_RESERVATIONS_SUCCESS';
export const REQUEST_RESERVATIONS_FAIL = 'REQUEST_RESERVATIONS_FAIL';

//ticket
export const CHANGE_TICKET_PANEL = 'CHANGE_TICKET_PANEL';

export const REQUEST_TICKET = 'REQUEST_TICKET';
export const REQUEST_TICKET_SUCCESS = 'REQUEST_TICKET_SUCCESS';
export const REQUEST_TICKET_FAIL = 'REQUEST_TICKET_FAIL';

//log
export const REQUEST_LOG = 'REQUEST_LOG';
export const REQUEST_LOG_SUCCESS = 'REQUEST_LOG_SUCCESS';
export const REQUEST_LOG_FAIL = 'REQUEST_LOG_FAIL';
export const SET_LOG_PAGE = 'SET_LOG_PAGE';
export const CLEAR_LOG = 'CLEAR_LOG';

//jwt token
export const SET_TEST_TOKEN = 'SET_TEST_TOKEN';
export const DELETE_TEST_TOKEN = 'DELETE_TEST_TOKEN';
export const SET_CONF_TOKEN = 'SET_CONF_TOKEN';
export const DELETE_CONF_TOKEN = 'DELETE_CONF_TOKEN';
