//change language
export const CANGE_LANG = 'CANGE_LANG';

//request user infomation
export const REQUEST_USERINFO = 'REQUEST_USERINFO';
export const REQUEST_USERINFO_SUCCESS = 'REQUEST_USERINFO_SUCCESS';
export const REQUEST_USERINFO_FAIL = 'REQUEST_USERINFO_FAIL';

//change page status
export const SIDEVAR_ON = 'SIDEVAR_ON';
export const SIDEVAR_OFF = 'SIDEVAR_OFF';
export const CHANGE_SIDEVAR = 'CHANGE_SIDEVAR';

//alert
export const ADD_ACCESS_ALERT = 'ADD_ACCESS_ALERT';
export const DELETE_ACCESS_ALERT = 'DELETE_ACCESS_ALERT';
export const ADD_VARIDATION_ALERT = 'ADD_VARIDATION_ALERT';
export const CLEAR_VARIDATION_ALERT = 'CLEAR_VARIDATION_ALERT';

//address
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS';



//Access user
export const REQUEST_USERS = 'REQUEST_USERS';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAIL = 'REQUEST_USERS_FAIL';
export const DO_ASYNC_ACTION = 'DO_ASYNC_ACTION';
export const DONE_ASYNC_ACTION = 'DONE_ASYNC_ACTION';

export const REQUEST_ROLES = 'REQUEST_ROLES';
export const REQUEST_ROLES_SUCCESS = 'REQUEST_ROLES_SUCCESS';
export const REQUEST_ROLES_FAIL = 'REQUEST_ROLES_FAIL';





export const UPDATE_USERINFO_TICKETS = 'UPDATE_USERINFO_TICKETS';
export const UPDATE_USERINFO_RESERVATION = 'UPDATE_USERINFO_RESERVATION';

export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';

//message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//timetable
export const SET_TYPE_STATUS = 'SET_TYPE_STATUS';
export const CHANGE_TYPE_CHECKED = 'CHANGE_TYPE_CHECKED';

export const SET_PLACE_STATUS = 'SET_PLACE_STATUS';
export const CHANGE_PLACE_ACTIVE = 'CHANGE_PLACE_ACTIVE';
export const CHANGE_PLACE_CHECKED = 'CHANGE_PLACE_CHECKED';

export const CHANGE_WEEK = 'CHANGE_WEEK';

export const REQUEST_TIMETABLE = 'REQUEST_TIMETABLE';
export const REQUEST_TIMETABLE_SUCCESS = 'REQUEST_TIMETABLE_SUCCESS';
export const REQUEST_TIMETABLE_FAIL = 'REQUEST_TIMETABLE_FAIL';
export const TIMETABLE_IS_OLD = 'TIMETABLE_IS_OLD';
export const SET_PLANS = 'SET_PLANS';

export const MODAL_ON = 'MODAL_ON';
export const MODAL_OFF = 'MODAL_OFF';

//reservations
export const REQUEST_RESERVATIONS = 'REQUEST_RESERVATIONS';
export const REQUEST_RESERVATIONS_SUCCESS = 'REQUEST_RESERVATIONS_SUCCESS';
export const REQUEST_RESERVATIONS_FAIL = 'REQUEST_RESERVATIONS_FAIL';

//ticket
export const CHANGE_TICKET_PANEL = 'CHANGE_TICKET_PANEL';

export const REQUEST_TICKET = 'REQUEST_TICKET';
export const REQUEST_TICKET_SUCCESS = 'REQUEST_TICKET_SUCCESS';
export const REQUEST_TICKET_FAIL = 'REQUEST_TICKET_FAIL';

//log
export const REQUEST_LOG = 'REQUEST_LOG';
export const REQUEST_LOG_SUCCESS = 'REQUEST_LOG_SUCCESS';
export const REQUEST_LOG_FAIL = 'REQUEST_LOG_FAIL';
export const SET_LOG_PAGE = 'SET_LOG_PAGE';
export const CLEAR_LOG = 'CLEAR_LOG';

//jwt token
export const SET_TEST_TOKEN = 'SET_TEST_TOKEN';
export const DELETE_TEST_TOKEN = 'DELETE_TEST_TOKEN';
export const SET_CONF_TOKEN = 'SET_CONF_TOKEN';
export const DELETE_CONF_TOKEN = 'DELETE_CONF_TOKEN';
